import React, { createContext, useContext, useState, useEffect } from 'react';
import Cookies from 'js-cookie';

interface LanguageContextType {
  language: 'en' | 'pt';
  setLanguage: (lang: 'en' | 'pt') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.overview': 'Overview',
    'nav.monitoring': 'Monitoring',
    'nav.mentions': 'Mentions',
    'nav.videos': 'My Channel',
    'nav.integrations': 'Integrations',
    'nav.settings': 'Settings',
    
    // Header
    'header.selectProject': 'Select Project',
    'header.createProject': 'Create Project',
    'header.profile': 'Profile',
    'header.logout': 'Logout',
    'header.notifications': 'Notifications',
    'header.language': 'Language',
    'header.theme': 'Theme',
    
    // Sidebar
    'sidebar.upgrade': 'Upgrade to Premium',
    'sidebar.upgradeDescription': 'Unlock all features and get unlimited access',
    'sidebar.aiInsights': 'AI Insights',
    'sidebar.aiThinking': 'AI is thinking...',
    'sidebar.refreshInsights': 'Refresh Insights',
    'sidebar.projectGoal': 'Project Goal',
    'sidebar.audience': 'Target Audience',
    
    // Overview
    'overview.totalMentions': 'Total Mentions',
    'overview.positiveSentiment': 'Positive Sentiment',
    'overview.leadsGenerated': 'Leads Generated',
    'overview.growthRate': 'Growth Rate',
    'overview.last7Days': 'Last 7 days',
    'overview.last30Days': 'Last 30 days',
    'overview.last90Days': 'Last 90 days',
    'overview.channels': 'Channels',
    'overview.videos': 'Videos',
    'overview.todayMentions': "Today's Mentions",
    'overview.reach': 'Reach',
    'overview.activities': 'Activities',
    'overview.engagements': 'Engagements',
    'overview.performance': 'Performance',
    'overview.traffic': 'Traffic',
    'overview.keywords': 'Keywords',
    
    // Processing
    'processing.title': 'Processing Your Project',
    'processing.subtitle': 'We are analyzing and processing your project data. This may take a few minutes.',
    'processing.searchingVideos': 'Searching for videos',
    'processing.analyzingContent': 'Analyzing content',
    'processing.extractingData': 'Extracting data',
    'processing.processingComments': 'Processing comments',
    'processing.generatingInsights': 'Generating insights',
    'processing.finalizing': 'Finalizing setup',
    'processing.completed': 'Processing completed!',
    'processing.error': 'Error during processing',
    
    // Settings
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.security': 'Security',
    'settings.keywords': 'Keywords',
    'settings.projectSettings': 'Project Settings',
    'settings.projectName': 'Project Name',
    'settings.company': 'Company',
    'settings.website': 'Website',
    'settings.audience': 'Target Audience',
    'settings.country': 'Country',
    'settings.keywordScanners': 'Keyword Scanners',
    'settings.addKeyword': 'Add Keyword',
    'settings.negativeKeywords': 'Negative Keywords',
    'settings.scanFrequency': 'Scan Frequency',
    'settings.youtubeActive': 'YouTube Active',
    'settings.enableNotifications': 'Enable Notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.darkMode': 'Dark Mode',
    'settings.language': 'Language',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteProject': 'Delete Project',
    'settings.saveChanges': 'Save Changes',
    'settings.discardChanges': 'Discard Changes',
    'settings.unsavedChanges': 'You have unsaved changes',
    'settings.selectProject': 'Select a project to view keyword scanners',
    'settings.negativeKeywordsDescription': 'Keywords that will be excluded from monitoring and analysis',
    'settings.noNegativeKeywords': 'No negative keywords set. Add keywords to exclude unwanted content.',
    'settings.addNegativeKeywordPlaceholder': 'Add new negative keyword',
    'settings.dataManagement': 'Data Management',
    'settings.dataRetention': 'Data retention period',
    'settings.projectStatus': 'Project Status',
    'settings.projectStatusDescription': 'Disabling the project will pause monitoring and integrations',
    'settings.projectActive': 'Project Active',
    'settings.projectDisabled': 'Project Disabled',
    'settings.exportData': 'Export Data',
    'settings.clearProjectData': 'Clear Project Data',
    'settings.accountSettings': 'Account Settings',
    'settings.fullName': 'Full Name',
    'settings.fullNamePlaceholder': 'Your full name',
    'settings.emailPlaceholder': 'your.email@example.com',
    'settings.contactAdmin': 'To change user data, please contact your administrator',
    'settings.notificationSettings': 'Notification Settings',
    'settings.dailySummary': 'Daily mentions summary',
    'settings.highPriorityAlerts': 'High priority alerts',
    'settings.weeklyReports': 'Weekly performance reports',
    'settings.newIntegrations': 'New integrations available',
    'settings.pushNotifications': 'Push Notifications',
    'settings.browserNotifications': 'Browser notifications',
    'settings.mobileNotifications': 'Mobile notifications',
    'settings.realTimeAlerts': 'Real-time alerts',
    'settings.themeSettings': 'Theme Settings',
    'settings.autoTheme': 'Auto (follows system)',
    'settings.lightTheme': 'Light',
    'settings.darkTheme': 'Dark',
    'settings.fontSize': 'Font Size',
    'settings.compactMode': 'Compact mode',
    'settings.changePassword': 'Change Password',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.loginSessions': 'Active Login Sessions',
    'settings.dataExport': 'Data Export',
    'settings.deleteAccount': 'Delete Account',
    'settings.dangerZoneDescription': 'These actions are irreversible',
    
    // Project Modal
    'project.createTitle': 'Create New Project',
    'project.editTitle': 'Edit Project',
    'project.name': 'Project Name',
    'project.namePlaceholder': 'Enter project name',
    'project.company': 'Company or product name',
    'project.companyPlaceholder': 'Enter your company or product name',
    'project.website': 'Home URL to project',
    'project.websitePlaceholder': 'www.example.com',
    'project.audience': 'Audience description',
    'project.audiencePlaceholder': 'Describe your target audience',
    'project.country': 'Country',
    'project.keywords': 'Keywords (separated by commas)',
    'project.keywordsPlaceholder': 'Keywords separated by commas (e.g. marketing, sales, product)',
    'project.generateKeywords': 'Generate with AI',
    'project.extractFromUrl': 'Extract from URL',
    'project.creating': 'Creating...',
    'project.create': 'Create Project',
    'project.cancel': 'Cancel',
    'project.save': 'Save',
    'project.fillRequired': 'Please fill in all required fields and add at least one keyword.',
    'project.error': 'Error creating the project. Please try again.',
    'project.urlError': 'Could not extract a description from this URL. Please try another URL or enter the description manually.',
    'project.timeout': 'The operation took too long to complete. This URL might be too complex to process or temporarily unavailable.',
    'project.corsError': 'Access to this URL is restricted. Please try a different URL.',
    
    // Integrations
    'integrations.title': 'Integrations',
    'integrations.youtube': 'YouTube',
    'integrations.reddit': 'Reddit',
    'integrations.linkedin': 'LinkedIn',
    'integrations.facebook': 'Facebook',
    'integrations.twitter': 'Twitter',
    'integrations.instagram': 'Instagram',
    'integrations.connected': 'Connected',
    'integrations.pending': 'Pending',
    'integrations.disconnected': 'Disconnected',
    'integrations.connect': 'Connect',
    'integrations.disconnect': 'Disconnect',
    'integrations.reconnect': 'Reconnect',
    'integrations.configure': 'Configure',
    'integrations.youtubeDesc': 'Monitor YouTube videos and comments. Engage with your audience by responding to comments.',
    'integrations.redditDesc': 'Track Reddit posts and comments mentioning your product. Engage with communities directly.',
    'integrations.linkedinDesc': 'Monitor LinkedIn posts and comments. Engage with professional audience.',
    'integrations.facebookDesc': 'Track Facebook posts and comments. Engage with users on the largest social network.',
    'integrations.twitterDesc': 'Monitor tweets and mentions. Engage with users through real-time conversations.',
    'integrations.instagramDesc': 'Track Instagram posts and comments. Engage with visual-focused audience.',
    
    // Monitoring
    'monitoring.title': 'Monitoring',
    'monitoring.liveData': 'Live Data',
    'monitoring.recentActivity': 'Recent Activity',
    'monitoring.alerts': 'Alerts',
    'monitoring.filters': 'Filters',
    'monitoring.sentiment': 'Sentiment',
    'monitoring.positive': 'Positive',
    'monitoring.neutral': 'Neutral',
    'monitoring.negative': 'Negative',
    'monitoring.platform': 'Platform',
    'monitoring.dateRange': 'Date Range',
    'monitoring.today': 'Today',
    'monitoring.yesterday': 'Yesterday',
    'monitoring.thisWeek': 'This Week',
    'monitoring.thisMonth': 'This Month',
    
    // Mentions
    'mentions.title': 'Mentions',
    'mentions.all': 'All Mentions',
    'mentions.unread': 'Unread',
    'mentions.responded': 'Responded',
    'mentions.pending': 'Pending Response',
    'mentions.reply': 'Reply',
    'mentions.markRead': 'Mark as Read',
    'mentions.markUnread': 'Mark as Unread',
    'mentions.viewOriginal': 'View Original',
    'mentions.noMentions': 'No mentions found',
    'mentions.loadMore': 'Load More',
    
    // Loading & Errors
    'loading.title': 'Loading...',
    'loading.projectData': 'Loading project data...',
    'loading.please_wait': 'Please wait',
    'error.general': 'An error occurred',
    'error.network': 'Network error. Please check your connection.',
    'error.unauthorized': 'Unauthorized access',
    'error.notFound': 'Resource not found',
    'error.tryAgain': 'Try Again',
    'error.goBack': 'Go Back',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember me',
    'auth.signInWith': 'Sign in with',
    'auth.signUpWith': 'Sign up with',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.lastWeek': 'Last Week',
    'common.thisMonth': 'This Month',
    'common.lastMonth': 'Last Month',
    'common.thisYear': 'This Year',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.tags': 'Tags',
    'common.url': 'URL',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.country': 'Country',
    'common.language': 'Language',
    'common.timezone': 'Timezone',
    'common.currency': 'Currency',
    'common.price': 'Price',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.quantity': 'Quantity',
    'common.amount': 'Amount',
    'common.percentage': 'Percentage',
    'common.count': 'Count',
    'common.score': 'Score',
    'common.rating': 'Rating',
    'common.rank': 'Rank',
    'common.level': 'Level',
    'common.priority': 'Priority',
    'common.importance': 'Importance',
    'common.urgency': 'Urgency',
    'common.frequency': 'Frequency',
    'common.duration': 'Duration',
    'common.interval': 'Interval',
    'common.range': 'Range',
    'common.limit': 'Limit',
    'common.minimum': 'Minimum',
    'common.maximum': 'Maximum',
    'common.average': 'Average',
    'common.median': 'Median',
    'common.mode': 'Mode',
    'common.variance': 'Variance',
    'common.deviation': 'Deviation',
    'common.correlation': 'Correlation',
    'common.regression': 'Regression',
    'common.trend': 'Trend',
    'common.pattern': 'Pattern',
    'common.anomaly': 'Anomaly',
    'common.outlier': 'Outlier',
    'common.threshold': 'Threshold',
    'common.baseline': 'Baseline',
    'common.benchmark': 'Benchmark',
    'common.metric': 'Metric',
    'common.kpi': 'KPI',
    'common.goal': 'Goal',
    'common.target': 'Target',
    'common.objective': 'Objective',
    'common.milestone': 'Milestone',
    'common.achievement': 'Achievement',
    'common.success': 'Success',
    'common.failure': 'Failure',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.debug': 'Debug',
    'common.trace': 'Trace',
    'common.log': 'Log',
    'common.history': 'History',
    'common.archive': 'Archive',
    'common.backup': 'Backup',
    'common.restore': 'Restore',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.sync': 'Sync',
    'common.update': 'Update',
    'common.upgrade': 'Upgrade',
    'common.downgrade': 'Downgrade',
    'common.install': 'Install',
    'common.uninstall': 'Uninstall',
    'common.configure': 'Configure',
    'common.customize': 'Customize',
    'common.personalize': 'Personalize',
    'common.optimize': 'Optimize',
    'common.analyze': 'Analyze',
    'common.monitor': 'Monitor',
    'common.track': 'Track',
    'common.measure': 'Measure',
    'common.evaluate': 'Evaluate',
    'common.assess': 'Assess',
    'common.audit': 'Audit',
    'common.review': 'Review',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'common.accept': 'Accept',
    'common.decline': 'Decline',
    'common.invite': 'Invite',
    'common.join': 'Join',
    'common.leave': 'Leave',
    'common.exit': 'Exit',
    'common.enter': 'Enter',
    'common.login': 'Login',
    'common.logout': 'Logout',
    'common.signin': 'Sign In',
    'common.signup': 'Sign Up',
    'common.register': 'Register',
    'common.subscribe': 'Subscribe',
    'common.unsubscribe': 'Unsubscribe',
    'common.follow': 'Follow',
    'common.unfollow': 'Unfollow',
    'common.like': 'Like',
    'common.unlike': 'Unlike',
    'common.favorite': 'Favorite',
    'common.unfavorite': 'Unfavorite',
    'common.bookmark': 'Bookmark',
    'common.unbookmark': 'Unbookmark',
    'common.star': 'Star',
    'common.unstar': 'Unstar',
    'common.rate': 'Rate',
    'common.comment': 'Comment',
    'common.reply': 'Reply',
    'common.mention': 'Mention',
    'common.tag': 'Tag',
    'common.untag': 'Untag',
    'common.flag': 'Flag',
    'common.unflag': 'Unflag',
    'common.report': 'Report',
    'common.block': 'Block',
    'common.unblock': 'Unblock',
    'common.ban': 'Ban',
    'common.unban': 'Unban',
    'common.mute': 'Mute',
    'common.unmute': 'Unmute',
    'common.hide': 'Hide',
    'common.show': 'Show',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.maximize': 'Maximize',
    'common.minimize': 'Minimize',
    'common.fullscreen': 'Fullscreen',
    'common.windowed': 'Windowed',
    'common.zoom': 'Zoom',
    'common.pan': 'Pan',
    'common.rotate': 'Rotate',
    'common.flip': 'Flip',
    'common.mirror': 'Mirror',
    'common.crop': 'Crop',
    'common.resizeAction': 'Resize',
    'common.scale': 'Scale',
    'common.stretch': 'Stretch',
    'common.fit': 'Fit',
    'common.fill': 'Fill',
    'common.contain': 'Contain',
    'common.cover': 'Cover',
    'common.center': 'Center',
    'common.align': 'Align',
    'common.justify': 'Justify',
    'common.distribute': 'Distribute',
    'common.space': 'Space',
    'common.margin': 'Margin',
    'common.padding': 'Padding',
    'common.border': 'Border',
    'common.outline': 'Outline',
    'common.shadow': 'Shadow',
    'common.glow': 'Glow',
    'common.blur': 'Blur',
    'common.focus': 'Focus',
    'common.highlight': 'Highlight',
    'common.selection': 'Selection',
    'common.cursor': 'Cursor',
    'common.pointer': 'Pointer',
    'common.hand': 'Hand',
    'common.grab': 'Grab',
    'common.grabbing': 'Grabbing',
    'common.move': 'Move',
    'common.drag': 'Drag',
    'common.drop': 'Drop',
    'common.crosshair': 'Crosshair',
    'common.text': 'Text',
    'common.wait': 'Wait',
    'common.help': 'Help',
    'common.notAllowed': 'Not Allowed',
    'common.auto': 'Auto',
    'common.default': 'Default',
    'common.inherit': 'Inherit',
    'common.initial': 'Initial',
    'common.unset': 'Unset',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.apply': 'Apply',
  },
  pt: {
    // Navigation
    'nav.overview': 'Visão Geral',
    'nav.monitoring': 'Monitoramento',
    'nav.mentions': 'Menções',
    'nav.videos': 'Meu Canal',
    'nav.integrations': 'Integrações',
    'nav.settings': 'Configurações',
    
    // Header
    'header.selectProject': 'Selecionar Projeto',
    'header.createProject': 'Criar Projeto',
    'header.profile': 'Perfil',
    'header.logout': 'Sair',
    'header.notifications': 'Notificações',
    'header.language': 'Idioma',
    'header.theme': 'Tema',
    
    // Sidebar
    'sidebar.upgrade': 'Upgrade para Premium',
    'sidebar.upgradeDescription': 'Desbloqueie todos os recursos e obtenha acesso ilimitado',
    'sidebar.aiInsights': 'Insights da IA',
    'sidebar.aiThinking': 'IA está pensando...',
    'sidebar.refreshInsights': 'Atualizar Insights',
    'sidebar.projectGoal': 'Objetivo do Projeto',
    'sidebar.audience': 'Público-Alvo',
    
    // Overview
    'overview.totalMentions': 'Total de Menções',
    'overview.positiveSentiment': 'Sentimento Positivo',
    'overview.leadsGenerated': 'Leads Gerados',
    'overview.growthRate': 'Taxa de Crescimento',
    'overview.last7Days': 'Últimos 7 dias',
    'overview.last30Days': 'Últimos 30 dias',
    'overview.last90Days': 'Últimos 90 dias',
    'overview.channels': 'Canais',
    'overview.videos': 'Vídeos',
    'overview.todayMentions': 'Menções de Hoje',
    'overview.reach': 'Alcance',
    'overview.activities': 'Atividades',
    'overview.engagements': 'Engajamentos',
    'overview.performance': 'Desempenho',
    'overview.traffic': 'Tráfego',
    'overview.keywords': 'Palavras-chave',
    
    // Processing
    'processing.title': 'Processando Seu Projeto',
    'processing.subtitle': 'Estamos analisando e processando os dados do seu projeto. Isso pode levar alguns minutos.',
    'processing.searchingVideos': 'Procurando vídeos',
    'processing.analyzingContent': 'Analisando conteúdo',
    'processing.extractingData': 'Extraindo dados',
    'processing.processingComments': 'Processando comentários',
    'processing.generatingInsights': 'Gerando insights',
    'processing.finalizing': 'Finalizando configuração',
    'processing.completed': 'Processamento concluído!',
    'processing.error': 'Erro durante o processamento',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.general': 'Geral',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificações',
    'settings.appearance': 'Aparência',
    'settings.security': 'Segurança',
    'settings.keywords': 'Palavras-chave',
    'settings.projectSettings': 'Configurações do Projeto',
    'settings.projectName': 'Nome do Projeto',
    'settings.company': 'Empresa',
    'settings.website': 'Site',
    'settings.audience': 'Público-Alvo',
    'settings.country': 'País',
    'settings.keywordScanners': 'Scanners de Palavras-chave',
    'settings.addKeyword': 'Adicionar Palavra-chave',
    'settings.negativeKeywords': 'Palavras-chave Negativas',
    'settings.scanFrequency': 'Frequência de Varredura',
    'settings.youtubeActive': 'YouTube Ativo',
    'settings.enableNotifications': 'Ativar Notificações',
    'settings.emailNotifications': 'Notificações por Email',
    'settings.darkMode': 'Modo Escuro',
    'settings.language': 'Idioma',
    'settings.dangerZone': 'Zona de Perigo',
    'settings.deleteProject': 'Excluir Projeto',
    'settings.saveChanges': 'Salvar Alterações',
    'settings.discardChanges': 'Descartar Alterações',
    'settings.unsavedChanges': 'Você tem alterações não salvas',
    'settings.selectProject': 'Selecione um projeto para ver os scanners de palavras-chave',
    'settings.negativeKeywordsDescription': 'Palavras-chave que serão excluídas do monitoramento e análise',
    'settings.noNegativeKeywords': 'Nenhuma palavra-chave negativa definida. Adicione palavras-chave para excluir conteúdo indesejado.',
    'settings.addNegativeKeywordPlaceholder': 'Adicionar nova palavra-chave negativa',
    'settings.dataManagement': 'Gerenciamento de Dados',
    'settings.dataRetention': 'Período de retenção de dados',
    'settings.projectStatus': 'Status do Projeto',
    'settings.projectStatusDescription': 'Desativar o projeto pausará o monitoramento e integrações',
    'settings.projectActive': 'Projeto Ativo',
    'settings.projectDisabled': 'Projeto Desativado',
    'settings.exportData': 'Exportar Dados',
    'settings.clearProjectData': 'Limpar Dados do Projeto',
    'settings.accountSettings': 'Configurações da Conta',
    'settings.fullName': 'Nome Completo',
    'settings.fullNamePlaceholder': 'Seu nome completo',
    'settings.emailPlaceholder': 'seu.email@exemplo.com',
    'settings.contactAdmin': 'Para alterar dados do usuário, entre em contato com o administrador',
    'settings.notificationSettings': 'Configurações de Notificação',
    'settings.dailySummary': 'Resumo diário de menções',
    'settings.highPriorityAlerts': 'Alertas de alta prioridade',
    'settings.weeklyReports': 'Relatórios semanais de desempenho',
    'settings.newIntegrations': 'Novas integrações disponíveis',
    'settings.pushNotifications': 'Notificações Push',
    'settings.browserNotifications': 'Notificações do navegador',
    'settings.mobileNotifications': 'Notificações móveis',
    'settings.realTimeAlerts': 'Alertas em tempo real',
    'settings.themeSettings': 'Configurações de Tema',
    'settings.autoTheme': 'Automático (segue o sistema)',
    'settings.lightTheme': 'Claro',
    'settings.darkTheme': 'Escuro',
    'settings.fontSize': 'Tamanho da Fonte',
    'settings.compactMode': 'Modo compacto',
    'settings.changePassword': 'Alterar Senha',
    'settings.twoFactorAuth': 'Autenticação de Dois Fatores',
    'settings.loginSessions': 'Sessões de Login Ativas',
    'settings.dataExport': 'Exportação de Dados',
    'settings.deleteAccount': 'Excluir Conta',
    'settings.dangerZoneDescription': 'Essas ações são irreversíveis',
    
    // Project Modal
    'project.createTitle': 'Criar Novo Projeto',
    'project.editTitle': 'Editar Projeto',
    'project.name': 'Nome do Projeto',
    'project.namePlaceholder': 'Digite o nome do projeto',
    'project.company': 'Nome da empresa ou produto',
    'project.companyPlaceholder': 'Digite o nome da sua empresa ou produto',
    'project.website': 'URL inicial do projeto',
    'project.websitePlaceholder': 'www.exemplo.com',
    'project.audience': 'Descrição do público',
    'project.audiencePlaceholder': 'Descreva seu público-alvo',
    'project.country': 'País',
    'project.keywords': 'Palavras-chave (separadas por vírgulas)',
    'project.keywordsPlaceholder': 'Palavras-chave separadas por vírgulas (ex: marketing, vendas, produto)',
    'project.generateKeywords': 'Gerar com IA',
    'project.extractFromUrl': 'Extrair da URL',
    'project.creating': 'Criando...',
    'project.create': 'Criar Projeto',
    'project.cancel': 'Cancelar',
    'project.save': 'Salvar',
    'project.fillRequired': 'Por favor, preencha todos os campos obrigatórios e adicione pelo menos uma palavra-chave.',
    'project.error': 'Erro ao criar o projeto. Tente novamente.',
    'project.urlError': 'Não foi possível extrair uma descrição desta URL. Tente outra URL ou digite a descrição manualmente.',
    'project.timeout': 'A operação demorou muito para ser concluída. Esta URL pode ser muito complexa para processar ou estar temporariamente indisponível.',
    'project.corsError': 'Acesso a esta URL é restrito. Tente uma URL diferente.',
    
    // Integrations
    'integrations.title': 'Integrações',
    'integrations.youtube': 'YouTube',
    'integrations.reddit': 'Reddit',
    'integrations.linkedin': 'LinkedIn',
    'integrations.facebook': 'Facebook',
    'integrations.twitter': 'Twitter',
    'integrations.instagram': 'Instagram',
    'integrations.connected': 'Conectado',
    'integrations.pending': 'Pendente',
    'integrations.disconnected': 'Desconectado',
    'integrations.connect': 'Conectar',
    'integrations.disconnect': 'Desconectar',
    'integrations.reconnect': 'Reconectar',
    'integrations.configure': 'Configurar',
    'integrations.youtubeDesc': 'Monitore vídeos e comentários do YouTube. Interaja com seu público respondendo aos comentários.',
    'integrations.redditDesc': 'Rastreie posts e comentários do Reddit mencionando seu produto. Interaja diretamente com as comunidades.',
    'integrations.linkedinDesc': 'Monitore posts e comentários do LinkedIn. Interaja com público profissional.',
    'integrations.facebookDesc': 'Rastreie posts e comentários do Facebook. Interaja com usuários na maior rede social.',
    'integrations.twitterDesc': 'Monitore tweets e menções. Interaja com usuários através de conversas em tempo real.',
    'integrations.instagramDesc': 'Rastreie posts e comentários do Instagram. Interaja com público focado em visual.',
    
    // Monitoring
    'monitoring.title': 'Monitoramento',
    'monitoring.liveData': 'Dados ao Vivo',
    'monitoring.recentActivity': 'Atividade Recente',
    'monitoring.alerts': 'Alertas',
    'monitoring.filters': 'Filtros',
    'monitoring.sentiment': 'Sentimento',
    'monitoring.positive': 'Positivo',
    'monitoring.neutral': 'Neutro',
    'monitoring.negative': 'Negativo',
    'monitoring.platform': 'Plataforma',
    'monitoring.dateRange': 'Período',
    'monitoring.today': 'Hoje',
    'monitoring.yesterday': 'Ontem',
    'monitoring.thisWeek': 'Esta Semana',
    'monitoring.thisMonth': 'Este Mês',
    
    // Mentions
    'mentions.title': 'Menções',
    'mentions.all': 'Todas as Menções',
    'mentions.unread': 'Não Lidas',
    'mentions.responded': 'Respondidas',
    'mentions.pending': 'Aguardando Resposta',
    'mentions.reply': 'Responder',
    'mentions.markRead': 'Marcar como Lida',
    'mentions.markUnread': 'Marcar como Não Lida',
    'mentions.viewOriginal': 'Ver Original',
    'mentions.noMentions': 'Nenhuma menção encontrada',
    'mentions.loadMore': 'Carregar Mais',
    
    // Loading & Errors
    'loading.title': 'Carregando...',
    'loading.projectData': 'Carregando dados do projeto...',
    'loading.please_wait': 'Aguarde',
    'error.general': 'Ocorreu um erro',
    'error.network': 'Erro de rede. Verifique sua conexão.',
    'error.unauthorized': 'Acesso não autorizado',
    'error.notFound': 'Recurso não encontrado',
    'error.tryAgain': 'Tentar Novamente',
    'error.goBack': 'Voltar',
    
    // Authentication
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.register': 'Registrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.rememberMe': 'Lembrar de mim',
    'auth.signInWith': 'Entrar com',
    'auth.signUpWith': 'Registrar com',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.dontHaveAccount': 'Não tem uma conta?',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Info',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.create': 'Criar',
    'common.update': 'Atualizar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.refresh': 'Atualizar',
    'common.clear': 'Limpar',
    'common.apply': 'Aplicar',
    'common.reset': 'Redefinir',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.ok': 'OK',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.back': 'Voltar',
    'common.close': 'Fechar',
    'common.add': 'Adicionar',
    'common.remove': 'Remover',
    'common.view': 'Visualizar',
    'common.download': 'Baixar',
    'common.upload': 'Enviar',
    'common.copy': 'Copiar',
    'common.paste': 'Colar',
    'common.cut': 'Recortar',
    'common.select': 'Selecionar',
    'common.selectAll': 'Selecionar Tudo',
    'common.deselectAll': 'Desselecionar Tudo',
    'common.sort': 'Ordenar',
    'common.share': 'Compartilhar',
    'common.submit': 'Enviar',
    'common.all': 'Todos',
    'common.none': 'Nenhum',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.enabled': 'Habilitado',
    'common.disabled': 'Desabilitado',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.today': 'Hoje',
    'common.yesterday': 'Ontem',
    'common.thisWeek': 'Esta Semana',
    'common.lastWeek': 'Semana Passada',
    'common.thisMonth': 'Este Mês',
    'common.lastMonth': 'Mês Passado',
    'common.thisYear': 'Este Ano',
    'common.status': 'Status',
    'common.date': 'Data',
    'common.time': 'Hora',
    'common.name': 'Nome',
    'common.description': 'Descrição',
    'common.type': 'Tipo',
    'common.category': 'Categoria',
    'common.tags': 'Tags',
    'common.url': 'URL',
    'common.email': 'Email',
    'common.phone': 'Telefone',
    'common.address': 'Endereço',
    'common.country': 'País',
    'common.language': 'Idioma',
    'common.timezone': 'Fuso Horário',
    'common.currency': 'Moeda',
    'common.price': 'Preço',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.quantity': 'Quantidade',
    'common.amount': 'Valor',
    'common.percentage': 'Porcentagem',
    'common.count': 'Contagem',
    'common.score': 'Pontuação',
    'common.rating': 'Avaliação',
    'common.rank': 'Classificação',
    'common.level': 'Nível',
    'common.priority': 'Prioridade',
    'common.importance': 'Importância',
    'common.urgency': 'Urgência',
    'common.frequency': 'Frequência',
    'common.duration': 'Duração',
    'common.interval': 'Intervalo',
    'common.range': 'Intervalo',
    'common.limit': 'Limite',
    'common.minimum': 'Mínimo',
    'common.maximum': 'Máximo',
    'common.average': 'Média',
    'common.median': 'Mediana',
    'common.mode': 'Moda',
    'common.variance': 'Variância',
    'common.deviation': 'Desvio',
    'common.correlation': 'Correlação',
    'common.regression': 'Regressão',
    'common.trend': 'Tendência',
    'common.pattern': 'Padrão',
    'common.anomaly': 'Anomalia',
    'common.outlier': 'Outlier',
    'common.threshold': 'Limite',
    'common.baseline': 'Linha de Base',
    'common.benchmark': 'Benchmark',
    'common.metric': 'Métrica',
    'common.kpi': 'KPI',
    'common.goal': 'Meta',
    'common.target': 'Alvo',
    'common.objective': 'Objetivo',
    'common.milestone': 'Marco',
    'common.achievement': 'Conquista',
    'common.failure': 'Falha',
    'common.debug': 'Debug',
    'common.trace': 'Rastreamento',
    'common.log': 'Log',
    'common.history': 'Histórico',
    'common.archive': 'Arquivo',
    'common.backup': 'Backup',
    'common.restore': 'Restaurar',
    'common.sync': 'Sincronizar',
    'common.upgrade': 'Atualizar',
    'common.downgrade': 'Fazer Downgrade',
    'common.install': 'Instalar',
    'common.uninstall': 'Desinstalar',
    'common.configure': 'Configurar',
    'common.customize': 'Personalizar',
    'common.personalize': 'Personalizar',
    'common.optimize': 'Otimizar',
    'common.analyze': 'Analisar',
    'common.monitor': 'Monitorar',
    'common.track': 'Rastrear',
    'common.measure': 'Medir',
    'common.evaluate': 'Avaliar',
    'common.assess': 'Avaliar',
    'common.audit': 'Auditar',
    'common.review': 'Revisar',
    'common.approve': 'Aprovar',
    'common.reject': 'Rejeitar',
    'common.accept': 'Aceitar',
    'common.decline': 'Recusar',
    'common.invite': 'Convidar',
    'common.join': 'Entrar',
    'common.leave': 'Sair',
    'common.exit': 'Sair',
    'common.enter': 'Entrar',
    'common.login': 'Login',
    'common.logout': 'Logout',
    'common.signin': 'Entrar',
    'common.signup': 'Registrar',
    'common.register': 'Registrar',
    'common.subscribe': 'Inscrever-se',
    'common.unsubscribe': 'Cancelar Inscrição',
    'common.follow': 'Seguir',
    'common.unfollow': 'Deixar de Seguir',
    'common.like': 'Curtir',
    'common.unlike': 'Descurtir',
    'common.favorite': 'Favoritar',
    'common.unfavorite': 'Desfavoritar',
    'common.bookmark': 'Favoritar',
    'common.unbookmark': 'Desfavoritar',
    'common.star': 'Estrela',
    'common.unstar': 'Remover Estrela',
    'common.rate': 'Avaliar',
    'common.comment': 'Comentar',
    'common.reply': 'Responder',
    'common.mention': 'Mencionar',
    'common.tag': 'Marcar',
    'common.untag': 'Desmarcar',
    'common.flag': 'Sinalizar',
    'common.unflag': 'Remover Sinalização',
    'common.report': 'Relatar',
    'common.block': 'Bloquear',
    'common.unblock': 'Desbloquear',
    'common.ban': 'Banir',
    'common.unban': 'Desbanir',
    'common.mute': 'Silenciar',
    'common.unmute': 'Ativar Som',
    'common.hide': 'Ocultar',
    'common.show': 'Mostrar',
    'common.expand': 'Expandir',
    'common.collapse': 'Recolher',
    'common.maximize': 'Maximizar',
    'common.minimize': 'Minimizar',
    'common.fullscreen': 'Tela Cheia',
    'common.windowed': 'Janela',
    'common.zoom': 'Zoom',
    'common.pan': 'Panorâmica',
    'common.rotate': 'Girar',
    'common.flip': 'Inverter',
    'common.mirror': 'Espelhar',
    'common.crop': 'Cortar',
    'common.resizeAction': 'Redimensionar',
    'common.scale': 'Escalar',
    'common.stretch': 'Esticar',
    'common.fit': 'Ajustar',
    'common.fill': 'Preencher',
    'common.contain': 'Conter',
    'common.cover': 'Cobrir',
    'common.center': 'Centralizar',
    'common.align': 'Alinhar',
    'common.justify': 'Justificar',
    'common.distribute': 'Distribuir',
    'common.space': 'Espaço',
    'common.margin': 'Margem',
    'common.padding': 'Preenchimento',
    'common.border': 'Borda',
    'common.outline': 'Contorno',
    'common.shadow': 'Sombra',
    'common.glow': 'Brilho',
    'common.blur': 'Desfoque',
    'common.focus': 'Foco',
    'common.highlight': 'Destacar',
    'common.selection': 'Seleção',
    'common.cursor': 'Cursor',
    'common.pointer': 'Ponteiro',
    'common.hand': 'Mão',
    'common.grab': 'Agarrar',
    'common.grabbing': 'Agarrando',
    'common.move': 'Mover',
    'common.drag': 'Arrastar',
    'common.drop': 'Soltar',
    'common.crosshair': 'Mira',
    'common.text': 'Texto',
    'common.wait': 'Aguardar',
    'common.help': 'Ajuda',
    'common.notAllowed': 'Não Permitido',
    'common.auto': 'Automático',
    'common.default': 'Padrão',
    'common.inherit': 'Herdar',
    'common.initial': 'Inicial',
    'common.unset': 'Desativar',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const getInitialLanguage = (): 'en' | 'pt' => {
    const savedLang = Cookies.get('language');
    if (savedLang === 'pt' || savedLang === 'en') {
      return savedLang;
    }
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('pt') ? 'pt' : 'en';
  };

  const [language, setLanguageState] = useState<'en' | 'pt'>(getInitialLanguage());

  const setLanguage = (lang: 'en' | 'pt') => {
    setLanguageState(lang);
    Cookies.set('language', lang, { expires: 365 });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};